# Generated by Django 4.1.7 on 2023-04-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_carmodel_rename_brand_carbrand_delete_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='production_date',
            field=models.DateTimeField(),
        ),
    ]
