# Generated by Django 4.1.7 on 2023-04-20 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_colour_alter_car_production_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='production_date',
        ),
        migrations.AddField(
            model_name='car',
            name='production_year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
